# %% [markdown]
# # Lab 10.4: Look at the data
#
# 1. Anscombe's quartet: identical statistics, different worlds. Saved as a figure.
# 2. An EDA pass over the shop: order value distribution (linear vs log), revenue by category (sorted bars), daily
#    orders over time with a planted "incident", binned means for a relationship.
# 3. A small report (markdown + PNGs) written to ./outputs, regenerable by running this file.
#
# Figures are saved, not shown (the lab runs headless). Open ./outputs/eda_report.md afterwards.

# %%
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "_shared"))
from shop import make_shop  # noqa: E402

OUT = Path(__file__).with_name("outputs")
OUT.mkdir(exist_ok=True)
report = ["# Rat & Co. EDA report", "", "Generated by `lab_10_4_eda.py`. Every figure below is regenerated on each run.", ""]

# %% [markdown]
# ## 1. Anscombe's quartet

# %%
x123 = np.array([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5], float)
ans = {
    "I": (x123, np.array([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68])),
    "II": (x123, np.array([9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74])),
    "III": (x123, np.array([7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73])),
    "IV": (np.array([8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8], float),
           np.array([6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89])),
}
fig, axes = plt.subplots(1, 4, figsize=(14, 3.2), sharex=True, sharey=True, constrained_layout=True)
stats = []
for ax, (name, (x, y)) in zip(axes, ans.items()):
    slope, intercept = np.polyfit(x, y, 1)
    r = np.corrcoef(x, y)[0, 1]
    stats.append((name, x.mean(), y.mean(), x.var(ddof=1), y.var(ddof=1), r, slope, intercept))
    ax.scatter(x, y, color="0.3")
    xs = np.array([3, 20])
    ax.plot(xs, intercept + slope * xs, color="C3")
    ax.set_title(f"{name}: r = {r:.3f}")
fig.suptitle("Anscombe's quartet: same statistics, same regression line, different data")
fig.savefig(OUT / "anscombe.png", dpi=120)
plt.close(fig)
st = pd.DataFrame(stats, columns=["set", "mean_x", "mean_y", "var_x", "var_y", "r", "slope", "intercept"]).round(2)
print(st.to_string(index=False))
assert st[["mean_x", "var_x"]].nunique().eq(1).all()
assert (st["mean_y"].round(1) == 7.5).all() and (st["r"].round(2) == 0.82).all() and (st["slope"].round(1) == 0.5).all()
report += ["## Anscombe's quartet", "", "![anscombe](anscombe.png)", "", st.to_markdown(index=False), ""]

# %% [markdown]
# ## 2. EDA on the shop
#
# We plant an incident: for 9 days, a tracking bug drops 70% of app orders. A daily plot shows it immediately;
# a monthly total barely does.

# %%
t = make_shop(n_customers=20_000, seed=8)
orders = t["orders"].copy()
rng = np.random.default_rng(8)
bug = (orders["channel"] == "app") & orders["order_ts"].between("2025-03-10", "2025-03-19") & (rng.uniform(size=len(orders)) < 0.7)
orders = orders[~bug]
lines = t["order_items"].merge(orders, on="order_id").merge(t["products"][["product_id", "category"]], on="product_id")
lines["amount"] = lines["quantity"] * lines["unit_price"]
order_value = lines.groupby("order_id")["amount"].sum()

# (a) distribution: linear vs log
fig, (a1, a2) = plt.subplots(1, 2, figsize=(11, 3.5), constrained_layout=True)
a1.hist(order_value, bins=60, color="0.6")
a1.set_xlabel("Order value (EUR)"); a1.set_ylabel("Orders"); a1.set_title("Linear axis: 'most orders are small'")
a2.hist(order_value, bins=np.logspace(np.log10(order_value.min()), np.log10(order_value.max()), 60), color="0.6")
a2.set_xscale("log"); a2.set_xlabel("Order value (EUR, log scale)")
med, mean = order_value.median(), order_value.mean()
for v, c, lbl in ((med, "C0", "median"), (mean, "C3", "mean")):
    a2.axvline(v, color=c); a2.text(v, a2.get_ylim()[1] * 0.9, f" {lbl} {v:.0f}", color=c)
a2.set_title("Log axis: the shape, and mean vs median")
fig.savefig(OUT / "order_value.png", dpi=120); plt.close(fig)
assert mean > med
top10_share = order_value.sort_values(ascending=False).head(int(0.1 * len(order_value))).sum() / order_value.sum()
report += ["## Order value", "", "![order value](order_value.png)", "",
           f"Median order {med:.0f} EUR, mean {mean:.0f} EUR. The top 10% of orders bring {top10_share:.0%} of revenue.", ""]

# (b) categories: sorted horizontal bars, one highlight
rev_cat = lines.groupby("category")["amount"].sum().sort_values()
fig, ax = plt.subplots(figsize=(7, 3.5), constrained_layout=True)
colors = ["C3" if c == rev_cat.idxmax() else "0.7" for c in rev_cat.index]
ax.barh(rev_cat.index, rev_cat.to_numpy() / 1e6, color=colors)
ax.set_xlabel("Revenue (million EUR)")
ax.set_title(f"{rev_cat.idxmax().title()} bring {rev_cat.max() / rev_cat.sum():.0%} of revenue")
fig.savefig(OUT / "revenue_by_category.png", dpi=120); plt.close(fig)
report += ["## Revenue by category", "", "![categories](revenue_by_category.png)", ""]

# (c) time: daily vs monthly
daily = orders.set_index("order_ts").groupby("channel").resample("D")["order_id"].count().unstack(0).fillna(0)
monthly = orders.set_index("order_ts").groupby("channel").resample("MS")["order_id"].count().unstack(0)
fig, (b1, b2) = plt.subplots(2, 1, figsize=(11, 5), constrained_layout=True)
b1.plot(monthly.index, monthly["app"], marker="o", color="0.4"); b1.set_title("App orders per month: a March dip you could easily explain away")
b2.plot(daily.index, daily["app"], color="0.4", lw=0.8)
b2.plot(daily.index, daily["app"].rolling(7, center=True).median(), color="C0", lw=1.5)
b2.axvspan(pd.Timestamp("2025-03-10"), pd.Timestamp("2025-03-19"), color="C3", alpha=0.2)
b2.set_title("App orders per day: a 9-day hole (a tracking bug, not a business problem)")
fig.savefig(OUT / "orders_over_time.png", dpi=120); plt.close(fig)
window = daily.loc["2025-03-10":"2025-03-18", "app"].mean()
baseline = daily.loc["2025-02-15":"2025-03-05", "app"].mean()
print(f"app orders/day: baseline {baseline:.1f}, during incident {window:.1f}")
assert window < 0.5 * baseline
report += ["## Orders over time", "", "![time](orders_over_time.png)", "",
           f"App orders fell from ~{baseline:.0f}/day to ~{window:.0f}/day between 2025-03-10 and 2025-03-18. "
           "Volume on web was stable, so this is most likely a tracking problem in the app. Checked with the app team before reporting.", ""]

# (d) relationship: binned means instead of an unreadable scatter
cust = (lines.groupby("customer_id").agg(orders=("order_id", "nunique"), revenue=("amount", "sum"))
        .join(t["customers"].set_index("customer_id")["signup_date"]))
cust["tenure_days"] = (pd.Timestamp("2025-12-31") - cust["signup_date"]).dt.days
cust["tenure_bin"] = pd.qcut(cust["tenure_days"], 10)
binned = cust.groupby("tenure_bin", observed=True)["orders"].agg(["mean", "sem"])
fig, ax = plt.subplots(figsize=(7, 3.5), constrained_layout=True)
mids = [iv.mid for iv in binned.index]
ax.errorbar(mids, binned["mean"], yerr=1.96 * binned["sem"], fmt="o-", color="C0", capsize=3)
ax.set_xlabel("Customer tenure (days, decile midpoints)"); ax.set_ylabel("Orders per customer (95% CI)")
ax.set_title("Binned means with confidence intervals")
fig.savefig(OUT / "tenure_vs_orders.png", dpi=120); plt.close(fig)
report += ["## Tenure vs orders", "", "![tenure](tenure_vs_orders.png)", ""]

# %% [markdown]
# ## 3. Write the report

# %%
(OUT / "eda_report.md").write_text("\n".join(report), encoding="utf-8")
pngs = sorted(p.name for p in OUT.glob("*.png"))
print("wrote", OUT / "eda_report.md", "with", pngs)
assert len(pngs) == 5 and all((OUT / p).stat().st_size > 5_000 for p in pngs)
print("\nAll checks passed.")
