"""Regenerate SYLLABUS.md, STATUS.md and every part/module README from course.yaml.

Run it after adding or moving a lesson:

    python tools/build_docs.py

It never touches lesson files. It only writes indexes, so it's safe to run as often as you like.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
COURSE = yaml.safe_load((ROOT / "course.yaml").read_text(encoding="utf-8"))

ROMAN = ["0", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]


def lesson_filename(lesson: dict) -> str:
    return f"{lesson['id']}-{lesson['slug']}.md"


def lesson_path(part: dict, module: dict, lesson: dict) -> Path:
    return ROOT / part["dir"] / module["dir"] / lesson_filename(lesson)


def lesson_written(path: Path) -> bool:
    # A lesson counts as written when it exists and is not marked as a draft.
    if not path.exists():
        return False
    return "<!-- draft -->" not in path.read_text(encoding="utf-8")


def labs_for(part: dict, module: dict) -> list[Path]:
    lab_dir = ROOT / part["dir"] / module["dir"] / "labs"
    return sorted(lab_dir.glob("lab_*.py")) if lab_dir.exists() else []


def rel(path: Path, start: Path) -> str:
    return path.relative_to(start).as_posix()


def build_syllabus() -> str:
    total_hours = sum(m["hours"] for p in COURSE["parts"] for m in p["modules"])
    n_modules = sum(len(p["modules"]) for p in COURSE["parts"])
    n_lessons = sum(len(m["lessons"]) for p in COURSE["parts"] for m in p["modules"])

    out = [
        "# Syllabus",
        "",
        f"*{COURSE['title']}*, by {COURSE['author']}",
        "",
        "This file is generated from `course.yaml` by `tools/build_docs.py`. Don't edit it by hand, I will",
        "overwrite your changes the next time I add a lesson and you will be sad.",
        "",
        f"**{len(COURSE['parts'])} parts, {n_modules} modules, {n_lessons} lessons, about {total_hours:,} hours of",
        "guided study.** Add roughly 30% on top for the time you will spend stuck on something stupid. That time",
        "is not wasted, it's the part where you actually learn.",
        "",
        "The hours are my honest estimate for someone who does every exercise and every lab. If you only read,",
        "divide by three, and then also divide what you retain by three.",
        "",
        "## Map",
        "",
        "| Part | Modules | Hours |",
        "|---|---|---|",
    ]
    for part in COURSE["parts"]:
        hours = sum(m["hours"] for m in part["modules"])
        mods = ", ".join(m["id"] for m in part["modules"])
        out.append(f"| [{ROMAN[part['id']]}. {part['title']}]({part['dir']}/) | {mods} | {hours} |")
    out.append("")

    for part in COURSE["parts"]:
        out += [f"## Part {ROMAN[part['id']]}: {part['title']}", "", part["blurb"].strip(), ""]
        for module in part["modules"]:
            mdir = f"{part['dir']}/{module['dir']}"
            out += [
                f"### Module {module['id']}: [{module['title']}]({mdir}/) ({module['hours']} h)",
                "",
                module["blurb"].strip(),
                "",
                "**When you finish it, you can:**",
                "",
            ]
            out += [f"- {o}" for o in module["outcomes"]]
            out += ["", "**Lessons:**", ""]
            for lesson in module["lessons"]:
                out.append(f"- {lesson['id']} [{lesson['title']}]({mdir}/{lesson_filename(lesson)})")
            out.append("")
    return "\n".join(out)


def build_status() -> str:
    rows = []
    done = total = 0
    for part in COURSE["parts"]:
        for module in part["modules"]:
            written = sum(lesson_written(lesson_path(part, module, l)) for l in module["lessons"])
            n = len(module["lessons"])
            done += written
            total += n
            labs = len(labs_for(part, module))
            state = "done" if written == n else ("in progress" if written else "not started")
            rows.append(
                f"| {module['id']} | [{module['title']}]({part['dir']}/{module['dir']}/) | {written}/{n} | {labs} | {state} |"
            )
    out = [
        "# Status",
        "",
        "Generated by `tools/build_docs.py`. A lesson counts as written when it's in the repo and not marked as a",
        "draft. A lab counts when it exists; CI runs every lab on every push, so if it's here, it passes.",
        "",
        f"**{done} of {total} lessons written.**",
        "",
        "| Module | Title | Lessons | Labs | State |",
        "|---|---|---|---|---|",
    ]
    out += rows
    out.append("")
    return "\n".join(out)


def build_part_readme(part: dict) -> str:
    hours = sum(m["hours"] for m in part["modules"])
    out = [
        f"# Part {ROMAN[part['id']]}: {part['title']}",
        "",
        part["blurb"].strip(),
        "",
        f"About {hours} hours in total.",
        "",
        "| Module | Hours | What it's about |",
        "|---|---|---|",
    ]
    for m in part["modules"]:
        out.append(f"| [{m['id']}. {m['title']}]({m['dir']}/) | {m['hours']} | {m['blurb'].strip()} |")
    out += ["", f"Back to the [syllabus](../SYLLABUS.md)."]
    return "\n".join(out) + "\n"


def build_module_readme(part: dict, module: dict) -> str:
    mdir = ROOT / part["dir"] / module["dir"]
    out = [
        f"# Module {module['id']}: {module['title']}",
        "",
        f"*Part {ROMAN[part['id']]}: {part['title']} · about {module['hours']} hours*",
        "",
        module["blurb"].strip(),
        "",
        "## Self-check",
        "",
        "If you can answer these without looking anything up, skim the lessons and go straight to the labs.",
        "If you can't, good, that's what the module is for.",
        "",
    ]
    out += [f"- {q}" for q in module["selfcheck"]]
    out += ["", "## When you finish it, you can", ""]
    out += [f"- {o}" for o in module["outcomes"]]
    out += ["", "## Lessons", ""]
    for lesson in module["lessons"]:
        path = lesson_path(part, module, lesson)
        mark = "" if lesson_written(path) else " *(coming soon)*"
        out.append(f"{lesson['id']}. [{lesson['title']}]({lesson_filename(lesson)}){mark}")
        out.append("")
    labs = labs_for(part, module)
    if labs:
        out += ["## Labs", "", "Run them from the repository root, for example:", "", "```bash"]
        out.append(f"python {rel(labs[0], ROOT)}")
        out += ["```", ""]
        for lab in labs:
            out.append(f"- [`{lab.name}`](labs/{lab.name})")
        out.append("")
    out.append(f"Back to [Part {ROMAN[part['id']]}](../) · [Syllabus](../../SYLLABUS.md)")
    return "\n".join(out) + "\n"


def main() -> None:
    (ROOT / "SYLLABUS.md").write_text(build_syllabus(), encoding="utf-8")
    (ROOT / "STATUS.md").write_text(build_status(), encoding="utf-8")
    for part in COURSE["parts"]:
        pdir = ROOT / part["dir"]
        pdir.mkdir(exist_ok=True)
        (pdir / "README.md").write_text(build_part_readme(part), encoding="utf-8")
        for module in part["modules"]:
            mdir = pdir / module["dir"]
            mdir.mkdir(exist_ok=True)
            (mdir / "README.md").write_text(build_module_readme(part, module), encoding="utf-8")
    print("docs rebuilt")


if __name__ == "__main__":
    main()
